"""rename department

Revision ID: 511a5d0853a4
Revises: 6fa2da50cde2
Create Date: 2024-01-07 17:08:27.160013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511a5d0853a4'
down_revision = '6fa2da50cde2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
